apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poc-demo

resources:
  - ../base

patches:
- target:
    kind: Ingress
    name: poc-app-stable
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: localhost
- target:
    kind: Ingress
    name: poc-app-canary
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: localhost