apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/simardeep1792/devsecops-poc
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: poc-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true