apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: poc-analysis
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 30s
    count: 5
    successCondition: result[0] >= 0.99
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring:9090
        query: |
          sum(rate(nginx_ingress_controller_requests{service="{{args.service-name}}",status!~"5.."}[1m])) / 
          sum(rate(nginx_ingress_controller_requests{service="{{args.service-name}}"}[1m]))
  - name: latency-p95
    interval: 30s
    count: 5
    successCondition: result[0] < 0.5
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring:9090
        query: |
          histogram_quantile(0.95, 
            sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{service="{{args.service-name}}"}[1m])) 
            by (le)
          )