apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poc-app-canary-header
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "x-testing"
    nginx.ingress.kubernetes.io/canary-by-header-value: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: poc-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: poc-app-canary
            port:
              number: 80