apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poc-demo

resources:
  - namespace.yaml
  - service-stable.yaml
  - service-canary.yaml
  - rollout.yaml
  - ingress-stable.yaml
  - ingress-canary.yaml