apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: poc-app
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
      annotations:
        rollme: "1"
    spec:
      containers:
      - name: poc-app
        image: simardeep1792/poc-app:v1.0.0
        env:
        - name: DEPLOYMENT_CHANNEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['role']
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
  strategy:
    canary:
      stableService: poc-app-stable
      canaryService: poc-app-canary
      scaleDownDelaySeconds: 30
      canaryMetadata:
        labels:
          role: canary
      stableMetadata:
        labels:
          role: stable
      trafficRouting:
        nginx:
          stableIngress: poc-app-stable
          additionalIngressAnnotations:
            canary-by-header: never
      steps:
      - setWeight: 0
      - pause: {}
      - setWeight: 20
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 80
      - pause: {}